### ISSUE TITLE
Make Sayaam for all info screen

### ISSUE THREAD

**Issue by VikAnalytics** [saayam-for-all/mobileapp#1]
**Description**
Change the button names to **_Create New Help Request_** and **_Promote Yourself to Voluntee_**r in our user dashboard page.

**Comment by Ashan-264** [comment]
Is this what you mean?

![Image](https://github.com/user-attachments/assets/9b74f275-68d0-46ca-a4eb-c38f00974704)

**Comment by rmb2020** [comment]
I think 'Change the button names to Create New Help Request and **Promote Yourself to Voluntee**r in our user dashboard page' is adding these  2 buttons on our home page after login. I think that part is done. Parth worked on it according to mockup.
