### ISSUE TITLE
Volunteer Promotion Wizard

### ISSUE THREAD

**Issue by rmb2020** [saayam-for-all/mobileapp#10]
Added this issue to add more info about 'Become a volunteer' wizard. Please refer to webapp issue link below when working on it.  https://github.com/saayam-for-all/webapp/issues/56

Promotion steps of the wizard. Links are from webapp project tracker. 
Step 1: https://github.com/orgs/saayam-for-all/projects/7?pane=issue&itemId=76511594
Step 2: https://github.com/orgs/saayam-for-all/projects/7?pane=issue&itemId=76511737

**Comment by ibarotparth** [comment]
Working on Availability Wizard Page

https://github.com/user-attachments/assets/27d66c47-fcb7-49f0-abec-9d44a16da5a7
