### ISSUE TITLE
Design Dashboard page

### ISSUE THREAD

**Issue by ibarotparth** [saayam-for-all/mobileapp#6]
- Top Bar
- Sear Bar
- My Request
- Managed Request
- Others Request
- Become Volunteer
- Create Request
- Tab Bar functionality

**Comment by RaoBhethanabotla** [comment]
Dashboard page is done in iOS. Checking with Android.

Working on Profile page.

**Comment by ibarotparth** [comment]
Fixed issues of Home Page with Android by working with @rmb2020 

Merge Rashmi Code and fixed issues of My Request, Managed request and other request in iOS.

Combine all our latest code into test branch.

Now, will start working on profile page.

**Comment by ibarotparth** [comment]
Will Start work on Fixing Grid Layout on Dashboard
