### ISSUE TITLE
Edit profile screen

### ISSUE THREAD

**Issue by rmb2020** [saayam-for-all/mobileapp#9]
Create Edit Profile screen according to UI mock up

**Comment by Ashan-264** [comment]
Made edit profile screen with easy navigation button 


![Image](https://github.com/user-attachments/assets/ca959205-8f0d-4050-8613-c791c3f25a78)

testing more on mobile for debugging

**Comment by Ashan-264** [comment]
added edit profile button to profile screen


![Image](https://github.com/user-attachments/assets/eafce143-c581-42ff-a0b3-0ed86753a9a0)



![Image](https://github.com/user-attachments/assets/eda6c278-7498-4581-b3a3-d21b29f090df)
